packages:
  # Public dev tooling & shared FE libraries (publishable)
  - 'extension-packages/*'

  # Shared backend (Laravel) libraries
  - 'handler-packages/*'

  # Submitted developer packages, pulled in for deploy
  - 'extensions/*'
  - 'handlers/*'
  - 'services/*'
